version: '3.7'

services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - microservicios_network_mv2

networks:
  microservicios_network_mv2:
    external: true